import 'reflect-metadata';
import {ValidationPipe,Controller,Get,Post,Body,Param,Headers,UnauthorizedException,Module,Injectable} from '@nestjs/common';
import {NestFactory} from '@nestjs/core'; import {SwaggerModule,DocumentBuilder} from '@nestjs/swagger'; import * as jwt from 'jsonwebtoken'; import argon2 from 'argon2'; import {PrismaClient} from '@prisma/client';
const db=new PrismaClient();
@Injectable() class AuthService { async login(email:string,password:string){const u=await db.user.findUnique({where:{email},include:{memberships:{include:{organization:true,role:true}}}});if(!u||!(await argon2.verify(u.passwordHash,password)))throw new UnauthorizedException('Invalid credentials');const m=u.memberships[0];if(!m)throw new UnauthorizedException('No organization membership');const secret=process.env.JWT_SECRET;if(!secret)throw new Error('JWT_SECRET is required');return {accessToken:jwt.sign({sub:u.id,organizationId:m.organizationId,role:m.role.name},secret,{expiresIn:'15m'}),user:{id:u.id,name:u.name,email:u.email},organization:m.organization};}}
@Controller('api/v1/auth') class AuthController {constructor(private readonly auth:AuthService){} @Post('login') login(@Body() b:{email:string;password:string}){return this.auth.login(b.email,b.password)}}
@Controller('api/v1') class AppController { @Get('health') health(){return {ok:true,service:'taxone-api',timestamp:new Date().toISOString()}} @Get('me') me(@Headers('authorization') h:string){if(!h?.startsWith('Bearer '))throw new UnauthorizedException();const secret=process.env.JWT_SECRET;if(!secret)throw new Error('JWT_SECRET is required');try{return jwt.verify(h.slice(7),secret)}catch{throw new UnauthorizedException()}} @Get('businesses') async businesses(@Headers('authorization') h:string){const p=this.payload(h);return db.business.findMany({where:{organizationId:p.organizationId},select:{id:true,legalName:true,tradeName:true,pan:true,gstRegistrations:true}})} @Get('businesses/:id/customers') async customers(@Headers('authorization') h:string,@Param('id') id:string){const p=this.payload(h);return db.customer.findMany({where:{businessId:id,business:{organizationId:p.organizationId}}})} @Post('businesses/:id/customers') async createCustomer(@Headers('authorization') h:string,@Param('id') id:string,@Body() b:{name:string;gstin?:string;pan?:string}){const p=this.payload(h);const biz=await db.business.findFirst({where:{id,organizationId:p.organizationId}});if(!biz)throw new UnauthorizedException();return db.customer.create({data:{businessId:id,...b}})} private payload(h:string){if(!h?.startsWith('Bearer '))throw new UnauthorizedException();try{return jwt.verify(h.slice(7),process.env.JWT_SECRET!) as {organizationId:string}}catch{throw new UnauthorizedException()}}}
@Module({controllers:[AuthController,AppController],providers:[AuthService]}) class AppModule{}
async function bootstrap(){const app=await NestFactory.create(AppModule);app.setGlobalPrefix('');app.useGlobalPipes(new ValidationPipe({whitelist:true,transform:true}));app.enableCors({origin:process.env.APP_URL??'http://localhost:3000',credentials:true});const config=new DocumentBuilder().setTitle('TaxOne API').setDescription('Independent Indian accounting and tax automation API').setVersion('1.0').addBearerAuth().build();SwaggerModule.setup('docs',app,SwaggerModule.createDocument(app,config));await app.listen(Number(process.env.PORT??4000));} bootstrap();
