import 'reflect-metadata';
import {ValidationPipe,Controller,Get,Post,Body,Param,Headers,UnauthorizedException,ForbiddenException,Module,Injectable} from '@nestjs/common';
import {NestFactory} from '@nestjs/core'; import {SwaggerModule,DocumentBuilder} from '@nestjs/swagger'; import * as jwt from 'jsonwebtoken'; import argon2 from 'argon2'; import {PrismaClient,InvoiceStatus} from '@prisma/client'; import {calculateTax} from '@taxone/gst';
const db=new PrismaClient();
type Claims={sub:string;organizationId:string;role:string};
function claims(h?:string):Claims{if(!h?.startsWith('Bearer '))throw new UnauthorizedException();try{return jwt.verify(h.slice(7),process.env.JWT_SECRET!) as Claims}catch{throw new UnauthorizedException()}}
@Injectable() class AuthService {async login(email:string,password:string){const u=await db.user.findUnique({where:{email},include:{memberships:{include:{organization:true,role:true}}}});if(!u||!(await argon2.verify(u.passwordHash,password)))throw new UnauthorizedException('Invalid credentials');const m=u.memberships[0];if(!m)throw new UnauthorizedException('No organization membership');const secret=process.env.JWT_SECRET;if(!secret)throw new Error('JWT_SECRET is required');return {accessToken:jwt.sign({sub:u.id,organizationId:m.organizationId,role:m.role.name},secret,{expiresIn:'15m'}),user:{id:u.id,name:u.name,email:u.email},organization:m.organization};}}
@Controller('api/v1/auth') class AuthController {constructor(private readonly auth:AuthService){} @Post('login') login(@Body() b:{email:string;password:string}){return this.auth.login(b.email,b.password)}}
@Controller('api/v1') class AppController {
@Get('health') health(){return {ok:true,service:'taxone-api',timestamp:new Date().toISOString()}}
@Get('me') me(@Headers('authorization') h:string){return claims(h)}
@Get('businesses') async businesses(@Headers('authorization') h:string){const p=claims(h);return db.business.findMany({where:{organizationId:p.organizationId},include:{gstRegistrations:true}})}
@Get('businesses/:id/customers') async customers(@Headers('authorization') h:string,@Param('id') id:string){const p=claims(h);return db.customer.findMany({where:{businessId:id,business:{organizationId:p.organizationId}}})}
@Post('businesses/:id/customers') async createCustomer(@Headers('authorization') h:string,@Param('id') id:string,@Body() b:{name:string;gstin?:string;pan?:string}){const p=claims(h);const biz=await db.business.findFirst({where:{id,organizationId:p.organizationId}});if(!biz)throw new ForbiddenException();return db.customer.create({data:{businessId:id,...b}})}
@Get('businesses/:id/invoices') async invoices(@Headers('authorization') h:string,@Param('id') id:string){const p=claims(h);return db.invoice.findMany({where:{businessId:id,business:{organizationId:p.organizationId}},include:{customer:true,items:true},orderBy:{invoiceDate:'desc'}})}
@Post('businesses/:id/invoices') async createInvoice(@Headers('authorization') h:string,@Param('id') id:string,@Body() b:{invoiceNumber:string;customerId?:string;invoiceDate?:string;placeOfSupply?:string;interState?:boolean;items:{itemId:string;description:string;quantity:number;rate:number;discount?:number;gstRate:number}[]}){const p=claims(h);const biz=await db.business.findFirst({where:{id,organizationId:p.organizationId},include:{gstRegistrations:true}});if(!biz)throw new ForbiddenException();const items=b.items.map(x=>{const taxable=x.quantity*x.rate-(x.discount??0);const t=calculateTax(taxable,x.gstRate,!!b.interState);return {...x,taxableValue:t.taxable.toFixed(2),cgst:t.cgst.toFixed(2),sgst:t.sgst.toFixed(2),igst:t.igst.toFixed(2),cess:t.cess.toFixed(2)}});const taxable=items.reduce((s,x)=>s+Number(x.taxableValue),0),cgst=items.reduce((s,x)=>s+Number(x.cgst),0),sgst=items.reduce((s,x)=>s+Number(x.sgst),0),igst=items.reduce((s,x)=>s+Number(x.igst),0),cess=items.reduce((s,x)=>s+Number(x.cess),0);return db.invoice.create({data:{businessId:id,customerId:b.customerId,invoiceNumber:b.invoiceNumber,invoiceDate:b.invoiceDate?new Date(b.invoiceDate):new Date(),placeOfSupply:b.placeOfSupply,reverseCharge:false,taxableValue:taxable,cgst,sgst,igst,cess,total:taxable+cgst+sgst+igst+cess,status:InvoiceStatus.VALIDATED,items:{create:items.map(x=>({itemId:x.itemId,description:x.description,quantity:x.quantity,rate:x.rate,discount:x.discount??0,taxableValue:x.taxableValue,cgst:x.cgst,sgst:x.sgst,igst:x.igst,cess:x.cess}))}}})}
@Post('businesses/:id/invoices/:invoiceId/post') async postInvoice(@Headers('authorization') h:string,@Param('id') id:string,@Param('invoiceId') invoiceId:string){const p=claims(h);const invoice=await db.invoice.findFirst({where:{id:invoiceId,businessId:id,business:{organizationId:p.organizationId}}});if(!invoice)throw new ForbiddenException();if(invoice.status===InvoiceStatus.POSTED||invoice.status===InvoiceStatus.PAID||invoice.status===InvoiceStatus.PARTIALLY_PAID)return invoice;const fy=await db.financialYear.findFirst({where:{businessId:id,startDate:{lte:invoice.invoiceDate},endDate:{gte:invoice.invoiceDate}}});const ar=await db.account.findFirst({where:{businessId:id,code:'1200'}}),sales=await db.account.findFirst({where:{businessId:id,code:'4000'}}),tax=await db.account.findFirst({where:{businessId:id,code:'5200'}});if(!fy||!ar||!sales||!tax)throw new ForbiddenException('Required chart of accounts is missing');return db.$transaction(async tx=>{const last=await tx.journalEntry.findFirst({where:{businessId:id},orderBy:{entryNumber:'desc'}});const je=await tx.journalEntry.create({data:{businessId:id,financialYearId:fy.id,entryNumber:(last?.entryNumber??0)+1,date:invoice.invoiceDate,narration:`Sales invoice ${invoice.invoiceNumber}`,sourceType:'INVOICE',sourceId:invoice.id,status:'POSTED',lines:{create:[{accountId:ar.id,debit:invoice.total,credit:0},{accountId:sales.id,debit:0,credit:invoice.taxableValue},{accountId:tax.id,debit:0,credit:Number(invoice.cgst)+Number(invoice.sgst)+Number(invoice.igst)+Number(invoice.cess)}]}}});const gst=await tx.gSTReturnRecord.create({data:{businessId:id,invoiceId:invoice.id,invoiceNumber:invoice.invoiceNumber,invoiceDate:invoice.invoiceDate,taxableValue:invoice.taxableValue,cgst:invoice.cgst,sgst:invoice.sgst,igst:invoice.igst,cess:invoice.cess,source:'SALES_BOOK'}});await tx.invoice.update({where:{id:invoice.id},data:{status:InvoiceStatus.POSTED}});await tx.auditLog.create({data:{organizationId:p.organizationId,userId:p.sub,action:'POST',entity:'Invoice',entityId:invoice.id,after:{journalEntryId:je.id,gstRecordId:gst.id}}});return tx.invoice.findUnique({where:{id:invoice.id},include:{items:true,gstRecords:true}})})}
}
@Module({controllers:[AuthController,AppController],providers:[AuthService]}) class AppModule{}
async function bootstrap(){const app=await NestFactory.create(AppModule);app.useGlobalPipes(new ValidationPipe({whitelist:true,transform:true}));app.enableCors({origin:process.env.APP_URL??'http://localhost:3000',credentials:true});const config=new DocumentBuilder().setTitle('TaxOne API').setDescription('Independent accounting and GST automation API').setVersion('1.0').addBearerAuth().build();SwaggerModule.setup('docs',app,SwaggerModule.createDocument(app,config));await app.listen(Number(process.env.PORT??4000));} bootstrap();
