import Decimal from 'decimal.js';
export type Line={accountId:string; debit:Decimal.Value; credit:Decimal.Value};
export type AccountType='ASSET'|'EXPENSE'|'LIABILITY'|'EQUITY'|'INCOME';
export type AccountSnapshot={accountId:string;name:string;type:AccountType;debit:Decimal.Value;credit:Decimal.Value};
export function assertBalanced(lines:Line[]):void { const debit=lines.reduce((s,l)=>s.plus(l.debit),new Decimal(0)); const credit=lines.reduce((s,l)=>s.plus(l.credit),new Decimal(0)); if(!debit.eq(credit)) throw new Error(`Unbalanced journal: debit ${debit.toFixed(2)} != credit ${credit.toFixed(2)}`); if(debit.lte(0)) throw new Error('Journal total must be positive'); for(const l of lines){const d=new Decimal(l.debit),c=new Decimal(l.credit);if(d.isNegative()||c.isNegative())throw new Error('Debit/credit cannot be negative');if(d.gt(0)&&c.gt(0))throw new Error('A journal line cannot contain both debit and credit');} }
export function accountBalance(debit:Decimal.Value,credit:Decimal.Value,type:AccountType){const d=new Decimal(debit),c=new Decimal(credit); return ['ASSET','EXPENSE'].includes(type)?d.minus(c):c.minus(d)}
export function trialBalance(lines:{accountId:string;debit:Decimal.Value;credit:Decimal.Value}[]){const m=new Map<string,{debit:Decimal;credit:Decimal}>(); for(const l of lines){const x=m.get(l.accountId)??{debit:new Decimal(0),credit:new Decimal(0)};x.debit=x.debit.plus(l.debit);x.credit=x.credit.plus(l.credit);m.set(l.accountId,x)} return m;}
export function runningBalance(lines:{date:Date;entryNumber:number;debit:Decimal.Value;credit:Decimal.Value}[]){let b=new Decimal(0);return [...lines].sort((a,c)=>a.date.getTime()-c.date.getTime()||a.entryNumber-c.entryNumber).map(x=>{b=b.plus(x.debit).minus(x.credit);return {...x,balance:b}})}
export function profitAndLoss(accounts:AccountSnapshot[]){let income=new Decimal(0),expense=new Decimal(0);for(const a of accounts){const b=accountBalance(a.debit,a.credit,a.type);if(a.type==='INCOME')income=income.plus(b);if(a.type==='EXPENSE')expense=expense.plus(b)}return {income,expense,netProfit:income.minus(expense)};}
export function balanceSheet(accounts:AccountSnapshot[],retainedEarnings:Decimal.Value=0){const assets=new Decimal(0),liabilities=new Decimal(0),equity=new Decimal(0);let assetTotal=assets,liabilityTotal=liabilities,equityTotal=equity;for(const a of accounts){const b=accountBalance(a.debit,a.credit,a.type);if(a.type==='ASSET')assetTotal=assetTotal.plus(b);else if(a.type==='LIABILITY')liabilityTotal=liabilityTotal.plus(b);else if(a.type==='EQUITY')equityTotal=equityTotal.plus(b)}return {assets:assetTotal,liabilities:liabilityTotal,equity:equityTotal.plus(retainedEarnings),difference:assetTotal.minus(liabilityTotal).minus(equityTotal).minus(retainedEarnings)};}
export function ledger(accounts:AccountSnapshot[],lines:{accountId:string;date:Date;entryNumber:number;debit:Decimal.Value;credit:Decimal.Value}[]){const by=new Map<string,typeof lines>();for(const l of lines){const list=by.get(l.accountId)??[];list.push(l);by.set(l.accountId,list)}return accounts.map(a=>({...a,entries:runningBalance(by.get(a.accountId)??[])}));}
